spring:
  config.activate.on-profile: prod
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

randommer:
  uri: ${RANDOMMER_URI}
  api-key: ${RANDOMMER_API_KEY}
